### ISSUE TITLE
Why should I use this library instead of RxDart?

### ISSUE THREAD

**Issue by andrewackerman** [renggli/dart-rx#9]
[RxDart](https://pub.dev/packages/rxdart) already exists which not only provides the ReactiveX behavior and interfaces in Dart, but does so by _extending_ native Dart streams instead of trying to replace them altogether. (It's also been around a while and has matured and been battle-tested in that time.)

This library's observables not being based on Dart streams seems to be a massive reason to _not_ use this library, and it seems like the only interoperability is a light observable type that wraps the Stream object without exposing it or any of its functionality. and aside from that, there doesn't seem to be any way for a Dart stream to listen to a Dart-Rx observable, which makes working with native stream functions or other third-party library streams incredibly difficult.

So to get to the point, what does this library offer that A) RxDart doesn't already provide, and B) outweighs the loss of nearly all native Stream interoperability?

**Comment by renggli** [comment]
As I write in [README.md](https://github.com/renggli/dart-rx/blob/master/README.md) this is experimental code, likely incomplete and potentially full of bugs. The package is at version `0.0.x`. You should probably not use it, unless you want to experiment and contribute fixes and improvements. Also you should accept breaking changes, serious bugs, performance and memory issues.

Listening to a Dart Stream/Future/Iterable is supported with `rx.fromStream/Future/Iterable(...)`. The other way around seems to be missing indeed, but should be easy to add. Feel free to create a pull or feature request.

I started this project because I wanted to learn how Rx works on the inside, and because of my frustration with Dart Streams. People asked me to publish this code.

I believe, this library provides a clean Reactive API in the style of RxJava/RxJs. Compared to Dart Streams it provides custom schedulers, synchronous testing, and a much simpler way to build transformations (I believe).

**Comment by renggli** [comment]
Update: 5a11b110914c6ffeb5e7804864dfd8b0bc00c63f provides `toFuture` and `toStream` for better interoperability.

**Comment by renggli** [comment]
Closing, as interoperability with Futures and Streams has been resolved long time ago.
